services:
  rss-news-api:
    build:
      context: ./
      dockerfile: Containerfile
    container_name: rss-news-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./container/rss-news-api:/app
    depends_on:
      - redis

  redis:
    image: docker.io/library/redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./container/redis-data:/data
