name: mycelia

services:
  mycelia-api:
    build:
      context: ./
      dockerfile: Containerfile
    container_name: mycelia-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "./container/mycelia-api:/data"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: docker.io/library/redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./container/redis-data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s