packages:
  - .

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - msgpackr-extract
  - protobufjs
  - unrs-resolver

patchedDependencies:
  '@nestia/core@8.0.5': patches/@nestia__core@8.0.5.patch
